/* Do not edit -- generated by csrc/capi/generate_static_switches.py. */
#define MATMUL_CONFIG_SWITCH(BM_VAR, BN_VAR, BK_VAR, R_VAR, STAGES_VAR, cM_VAR, cN_VAR, ...) \
	do { \
		MATMUL_CONFIG_OPTION(BM_VAR, BN_VAR, BK_VAR, R_VAR, STAGES_VAR, cM_VAR, cN_VAR, 128, 256, 128, 64, 3, 1, 1, __VA_ARGS__); \
		MATMUL_CONFIG_OPTION(BM_VAR, BN_VAR, BK_VAR, R_VAR, STAGES_VAR, cM_VAR, cN_VAR, 128, 256, 128, 128, 3, 1, 1, __VA_ARGS__); \
	} while(0)
