/* Do not edit -- generated by csrc/capi/generate_static_switches.py. */
#define NOISING_A_CONFIG_SWITCH(BM_VAR, BK_VAR, R_VAR, STAGES_VAR, AxEBL_TYPE_VAR, ...) \
	do { \
		NOISING_A_CONFIG_OPTION(BM_VAR, BK_VAR, R_VAR, STAGES_VAR, AxEBL_TYPE_VAR, 64, 64, 64, 2, torch::kFloat16, cutlass::half_t, __VA_ARGS__); \
		NOISING_A_CONFIG_OPTION(BM_VAR, BK_VAR, R_VAR, STAGES_VAR, AxEBL_TYPE_VAR, 64, 64, 64, 2, torch::kInt32, int, __VA_ARGS__); \
		NOISING_A_CONFIG_OPTION(BM_VAR, BK_VAR, R_VAR, STAGES_VAR, AxEBL_TYPE_VAR, 64, 64, 128, 2, torch::kFloat16, cutlass::half_t, __VA_ARGS__); \
		NOISING_A_CONFIG_OPTION(BM_VAR, BK_VAR, R_VAR, STAGES_VAR, AxEBL_TYPE_VAR, 64, 64, 128, 2, torch::kInt32, int, __VA_ARGS__); \
	} while(0)
