#if !defined(DISABLE_R64)
#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_gemm_host.h"

    /* Autogenerated -- see generate_instantiations.py
    * run_pearl_gemm_<ElementOut, R, bM, bN, kStages, cM, cN, SkipReduction, SkipDenoising, EnableDebug>(PearlAPIParams& params, cudaStream_t stream);
    */

    	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, false, false, false, false>(PearlAPIParams&, cudaStream_t);
#if !defined(DISABLE_SKIP_C_STORE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, false, false, false, true>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_DEBUG_MODE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, false, false, true, false>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_DEBUG_MODE) && !defined(DISABLE_SKIP_C_STORE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, false, false, true, true>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_DENOISING)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, false, true, false, false>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_DENOISING) && !defined(DISABLE_SKIP_C_STORE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, false, true, false, true>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_DENOISING) && !defined(DISABLE_DEBUG_MODE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, false, true, true, false>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_DENOISING) && !defined(DISABLE_DEBUG_MODE) && !defined(DISABLE_SKIP_C_STORE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, false, true, true, true>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_REDUCTION)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, true, false, false, false>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_REDUCTION) && !defined(DISABLE_SKIP_C_STORE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, true, false, false, true>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_REDUCTION) && !defined(DISABLE_DEBUG_MODE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, true, false, true, false>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_REDUCTION) && !defined(DISABLE_DEBUG_MODE) && !defined(DISABLE_SKIP_C_STORE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, true, false, true, true>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_REDUCTION) && !defined(DISABLE_SKIP_DENOISING)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, true, true, false, false>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_REDUCTION) && !defined(DISABLE_SKIP_DENOISING) && !defined(DISABLE_SKIP_C_STORE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, true, true, false, true>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_REDUCTION) && !defined(DISABLE_SKIP_DENOISING) && !defined(DISABLE_DEBUG_MODE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, true, true, true, false>(PearlAPIParams&, cudaStream_t);
#endif
#if !defined(DISABLE_SKIP_REDUCTION) && !defined(DISABLE_SKIP_DENOISING) && !defined(DISABLE_DEBUG_MODE) && !defined(DISABLE_SKIP_C_STORE)
	template void run_pearl_gemm_<cutlass::bfloat16_t, 64, 128, 256, 128, 3, 1, 1, true, true, true, true>(PearlAPIParams&, cudaStream_t);
#endif
#endif // #if !defined(DISABLE_R64)