#if !defined(DISABLE_R128)
#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_noisingA_host.h"

    /* Autogenerated -- see generate_instantiations.py
    * run_pearl_noising_A_<ElementDenoise_AxEBL, R, bM_noising_A, bK_noising_A, kStages>(PearlAPIParams& params, cudaStream_t stream);
    */

    	template void run_pearl_noising_A_<cutlass::half_t, 128, 64, 64, 2>(PearlAPIParams&, cudaStream_t);
#endif