#if !defined(DISABLE_R64)
#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_noisingB_host.h"

    /* Autogenerated -- see generate_instantiations.py
    * run_pearl_noising_B_<ElementDenoise_EARxBpEB, R, bN_noising_B, bK_noising_B, kStages>(PearlAPIParams& params, cudaStream_t stream);
    */

    	template void run_pearl_noising_B_< cutlass::half_t, 64, 64, 64, 2>(PearlAPIParams&, cudaStream_t);
#endif