// SM80-compatible BSeed -> resident-B + tensor_hash stage-1 kernel.
//
// This mirrors MerkleTreeRootsKernelSM80, but replaces the global-memory leaf
// load with BSeed XOF generation. Each thread generates one 1024-byte B leaf,
// writes it to resident dB, hashes the generated bytes, then the existing
// Merkle reducers consume the per-block roots.
#pragma once

#include "blake3/blake3.cuh"
#include "cute/layout.hpp"
#include "cute/tensor.hpp"
#include "merkle_tree_utils.hpp"
#include "tensor_hash_constants.cuh"

#include <cutlass/array.h>
#include <cutlass/cutlass.h>
#include <cutlass/detail/layout.hpp>
#include <cutlass/gemm/collective/builders/sm90_common.inl>

namespace pearl {

using namespace cute;

struct BSeedBlock {
  uint32_t word[16];
};

namespace bseed_detail {

CUTLASS_DEVICE
uint32_t rotr32(uint32_t x, uint32_t n) {
  return (x >> n) | (x << (32 - n));
}

CUTLASS_DEVICE
void g(uint32_t& a, uint32_t& b, uint32_t& c, uint32_t& d,
       uint32_t mx, uint32_t my) {
  a = a + b + mx;
  d = rotr32(d ^ a, 16);
  c = c + d;
  b = rotr32(b ^ c, 12);
  a = a + b + my;
  d = rotr32(d ^ a, 8);
  c = c + d;
  b = rotr32(b ^ c, 7);
}

CUTLASS_DEVICE
void round(uint32_t s[16], const uint32_t m[16]) {
  g(s[0], s[4], s[8],  s[12], m[0],  m[1]);
  g(s[1], s[5], s[9],  s[13], m[2],  m[3]);
  g(s[2], s[6], s[10], s[14], m[4],  m[5]);
  g(s[3], s[7], s[11], s[15], m[6],  m[7]);
  g(s[0], s[5], s[10], s[15], m[8],  m[9]);
  g(s[1], s[6], s[11], s[12], m[10], m[11]);
  g(s[2], s[7], s[8],  s[13], m[12], m[13]);
  g(s[3], s[4], s[9],  s[14], m[14], m[15]);
}

CUTLASS_DEVICE
void permute(uint32_t m[16]) {
  uint32_t t0 = m[0],  t1 = m[1],  t2 = m[2],  t3 = m[3];
  uint32_t t4 = m[4],  t5 = m[5],  t6 = m[6],  t7 = m[7];
  uint32_t t8 = m[8],  t9 = m[9],  t10 = m[10], t11 = m[11];
  uint32_t t12 = m[12], t13 = m[13], t14 = m[14], t15 = m[15];
  m[0] = t2;   m[1] = t6;   m[2] = t3;   m[3] = t10;
  m[4] = t7;   m[5] = t0;   m[6] = t4;   m[7] = t13;
  m[8] = t1;   m[9] = t11;  m[10] = t12; m[11] = t5;
  m[12] = t9;  m[13] = t14; m[14] = t15; m[15] = t8;
}

CUTLASS_DEVICE
void xof_compress(const BSeedBlock& seed_block, uint64_t counter,
                  uint32_t out[16]) {
  uint32_t s[16];
  uint32_t m[16];

  CUTLASS_PRAGMA_UNROLL
  for (int i = 0; i < 16; ++i) {
    m[i] = seed_block.word[i];
  }

  s[0] = blake3::IV0; s[1] = blake3::IV1; s[2] = blake3::IV2; s[3] = blake3::IV3;
  s[4] = blake3::IV4; s[5] = blake3::IV5; s[6] = blake3::IV6; s[7] = blake3::IV7;
  s[8] = blake3::IV0; s[9] = blake3::IV1; s[10] = blake3::IV2; s[11] = blake3::IV3;
  s[12] = static_cast<uint32_t>(counter);
  s[13] = static_cast<uint32_t>(counter >> 32);
  s[14] = 32u;
  s[15] = blake3::CHUNK_START | blake3::CHUNK_END | blake3::ROOT;

  CUTLASS_PRAGMA_UNROLL
  for (int i = 0; i < 6; ++i) {
    round(s, m);
    permute(m);
  }
  round(s, m);

  out[0] = s[0] ^ s[8];
  out[1] = s[1] ^ s[9];
  out[2] = s[2] ^ s[10];
  out[3] = s[3] ^ s[11];
  out[4] = s[4] ^ s[12];
  out[5] = s[5] ^ s[13];
  out[6] = s[6] ^ s[14];
  out[7] = s[7] ^ s[15];
  out[8] = s[8] ^ blake3::IV0;
  out[9] = s[9] ^ blake3::IV1;
  out[10] = s[10] ^ blake3::IV2;
  out[11] = s[11] ^ blake3::IV3;
  out[12] = s[12] ^ blake3::IV4;
  out[13] = s[13] ^ blake3::IV5;
  out[14] = s[14] ^ blake3::IV6;
  out[15] = s[15] ^ blake3::IV7;
}

CUTLASS_DEVICE
uint32_t map_byte(uint32_t x) {
  return static_cast<uint32_t>(
      static_cast<uint8_t>(static_cast<int32_t>(x % 127u) - 63));
}

CUTLASS_DEVICE
uint32_t pack_mapped_word(uint32_t x) {
  uint32_t b0 = map_byte(x & 0xFFu);
  uint32_t b1 = map_byte((x >> 8) & 0xFFu);
  uint32_t b2 = map_byte((x >> 16) & 0xFFu);
  uint32_t b3 = map_byte((x >> 24) & 0xFFu);
  return b0 | (b1 << 8) | (b2 << 16) | (b3 << 24);
}

}  // namespace bseed_detail

template <int kNumThreads>
class BSeedMerkleTreeRootsKernelSM80 {
 public:
  using Element = uint8_t;

  static constexpr int kChunkSize = 1024;
  static constexpr int kWordSize = 4;
  static constexpr int kNumBlocksPerChunk =
      kChunkSize / blake3::MSG_BLOCK_SIZE;
  static constexpr int kNumWordsPerBlock =
      blake3::MSG_BLOCK_SIZE / sizeof(uint32_t);

  static constexpr uint32_t MaxThreadsPerBlock = kNumThreads;
  static constexpr uint32_t MinBlocksPerMultiprocessor = 1;

  using RmemLayoutChainingValue =
      Layout<Shape<Int<blake3::CHAINING_VALUE_SIZE_U32>>>;
  using RmemLayoutBlock = Layout<Shape<Int<kNumWordsPerBlock>>>;

  using SmemLayoutAtomLeaves = GMMA::Layout_K_SW128_Atom<uint32_t>;
  using SmemLayoutLeaves = decltype(tile_to_shape(
      SmemLayoutAtomLeaves{},
      Shape<Int<blake3::CHAINING_VALUE_SIZE_U32>, Int<kNumThreads>>{}));

  static constexpr size_t AlignmentLeaves =
      cutlass::detail::alignment_for_swizzle(SmemLayoutLeaves{});

  struct SharedStorage : cute::aligned_struct<AlignmentLeaves> {
    cute::array_aligned<uint32_t,
                        cute::cosize_v<SmemLayoutLeaves>,
                        AlignmentLeaves>
        smem_leaves;
  };

  static constexpr int SharedStorageSize = sizeof(SharedStorage);

  struct Arguments {
    BSeedBlock seed_block;
    Element* ptr_data;
    uint32_t data_len;
    Element* ptr_roots;
    Element* ptr_leaf_cvs;
  };

  // MSVC cannot pass a by-value function parameter aligned above 16 bytes
  // (error C2719), and CUTLASS launches kernels with Params by value. The
  // 128-byte alignment is defensive over-alignment, not required for
  // correctness — cap it on MSVC; other host compilers keep 128.
#ifndef PEARL_PARAMS_ALIGN
#  if defined(_MSC_VER)
#    define PEARL_PARAMS_ALIGN 16
#  else
#    define PEARL_PARAMS_ALIGN 128
#  endif
#endif
  struct alignas(PEARL_PARAMS_ALIGN) Params {
    BSeedBlock seed_block;
    Element* ptr_data;
    uint32_t data_len;
    Element* ptr_roots;
    Element* ptr_leaf_cvs;
  };

  static Params to_underlying_arguments(Arguments const& args) {
    return {args.seed_block, args.ptr_data, args.data_len, args.ptr_roots,
            args.ptr_leaf_cvs};
  }

  static dim3 get_grid_shape(Params const& params) {
    const size_t num_chunks =
        (params.data_len + kChunkSize - 1) / kChunkSize;
    return dim3((num_chunks + kNumThreads - 1) / kNumThreads);
  }

  static dim3 get_block_shape() { return dim3(kNumThreads); }

  CUTLASS_DEVICE
  void operator()(Params const& params, char* smem_buf) {
    SharedStorage& shared_storage =
        *reinterpret_cast<SharedStorage*>(smem_buf);
    const int tid = threadIdx.x;

    Tensor sLeaves = as_position_independent_swizzle_tensor(make_tensor(
        make_smem_ptr(shared_storage.smem_leaves.data()), SmemLayoutLeaves{}));

    const size_t num_chunks =
        (params.data_len + kChunkSize - 1) / kChunkSize;
    const size_t num_grid_blocks =
        (num_chunks + kNumThreads - 1) / kNumThreads;

    Tensor mRoots = make_tensor(
        reinterpret_cast<uint32_t*>(params.ptr_roots),
        make_layout(
            make_shape(Int<blake3::CHAINING_VALUE_SIZE_U32>{}, num_grid_blocks),
            make_stride(Int<1>{}, Int<blake3::CHAINING_VALUE_SIZE_U32>{})));

    const uint32_t global_chunk_idx = blockIdx.x * kNumThreads + tid;
    const bool has_chunk = (global_chunk_idx < num_chunks);

    Tensor rChainingValue = make_tensor<uint32_t>(RmemLayoutChainingValue{});
    CUTLASS_PRAGMA_UNROLL
    for (int i = 0; i < blake3::CHAINING_VALUE_SIZE_U32; ++i) {
      rChainingValue(i) = c_key[i];
    }

    if (has_chunk) {
      uint32_t* chunk_ptr = reinterpret_cast<uint32_t*>(
          params.ptr_data + static_cast<size_t>(global_chunk_idx) * kChunkSize);
      const uint32_t chunk_start_byte =
          static_cast<uint32_t>(global_chunk_idx) * kChunkSize;
      const uint32_t chunk_valid_bytes =
          (chunk_start_byte + kChunkSize <= params.data_len)
              ? static_cast<uint32_t>(kChunkSize)
              : (params.data_len - chunk_start_byte);

      CUTLASS_PRAGMA_NO_UNROLL
      for (int blk = 0; blk < kNumBlocksPerChunk; ++blk) {
        Tensor rBlock = make_tensor<uint32_t>(RmemLayoutBlock{});

        uint32_t xof[16];
        bseed_detail::xof_compress(
            params.seed_block,
            static_cast<uint64_t>(global_chunk_idx) * kNumBlocksPerChunk + blk,
            xof);

        const int word_base = blk * kNumWordsPerBlock;
        const uint32_t block_start_byte = blk * blake3::MSG_BLOCK_SIZE;

        if (block_start_byte + blake3::MSG_BLOCK_SIZE <= chunk_valid_bytes) {
          CUTLASS_PRAGMA_UNROLL
          for (int w = 0; w < kNumWordsPerBlock; ++w) {
            uint32_t mapped = bseed_detail::pack_mapped_word(xof[w]);
            chunk_ptr[word_base + w] = mapped;
            rBlock(w) = mapped;
          }
        } else {
          CUTLASS_PRAGMA_UNROLL
          for (int w = 0; w < kNumWordsPerBlock; ++w) {
            const uint32_t word_byte = block_start_byte + w * sizeof(uint32_t);
            uint32_t mapped = bseed_detail::pack_mapped_word(xof[w]);
            if (word_byte + sizeof(uint32_t) <= chunk_valid_bytes) {
              chunk_ptr[word_base + w] = mapped;
              rBlock(w) = mapped;
            } else if (word_byte < chunk_valid_bytes) {
              uint32_t valid = chunk_valid_bytes - word_byte;
              uint32_t mask = (1u << (valid * 8)) - 1u;
              uint8_t* byte_ptr =
                  reinterpret_cast<uint8_t*>(chunk_ptr + word_base + w);
              CUTLASS_PRAGMA_UNROLL
              for (uint32_t b = 0; b < 4; ++b) {
                if (b < valid) {
                  byte_ptr[b] = static_cast<uint8_t>((mapped >> (b * 8)) & 0xFFu);
                }
              }
              rBlock(w) = mapped & mask;
            } else {
              rBlock(w) = 0;
            }
          }
        }

        blake3::CompressParams cp{
            .counter = global_chunk_idx,
            .block_len = blake3::MSG_BLOCK_SIZE,
            .flags = blake3::KEYED_HASH};
        if (blk == 0)
          cp.flags |= blake3::CHUNK_START;
        if (blk == kNumBlocksPerChunk - 1)
          cp.flags |= blake3::CHUNK_END;

        blake3::compress_msg_block_u32(rBlock, rChainingValue, cp);
      }
    }

    CUTLASS_PRAGMA_UNROLL
    for (int i = 0; i < blake3::CHAINING_VALUE_SIZE_U32; ++i) {
      if (has_chunk && params.ptr_leaf_cvs != nullptr) {
        uint32_t* leaf_cv_ptr =
            reinterpret_cast<uint32_t*>(params.ptr_leaf_cvs) +
            static_cast<size_t>(global_chunk_idx) * blake3::CHAINING_VALUE_SIZE_U32;
        leaf_cv_ptr[i] = rChainingValue(i);
      }
      sLeaves(i, tid) = rChainingValue(i);
    }

    __syncthreads();

    const size_t bid = blockIdx.x;
    const bool is_last_block = (bid == num_grid_blocks - 1);

    const uint32_t num_leaves = [&]() -> uint32_t {
      if (!is_last_block)
        return static_cast<uint32_t>(kNumThreads);
      const uint32_t chunks_in_this_block = num_chunks % kNumThreads;
      const uint32_t actual =
          (chunks_in_this_block == 0) ? static_cast<uint32_t>(kNumThreads)
                                      : chunks_in_this_block;
      const uint32_t remainder_bytes = params.data_len % kChunkSize;
      const bool last_chunk_too_small =
          (remainder_bytes > 0) && (remainder_bytes < blake3::MSG_BLOCK_SIZE);
      return last_chunk_too_small ? (actual > 0 ? actual - 1 : 0) : actual;
    }();

    if (!is_last_block) {
      merkle_tree_utils::compute_perfect_mt<false>(sLeaves, kNumThreads);
    } else {
      if ((num_leaves & (num_leaves - 1)) == 0) {
        merkle_tree_utils::compute_perfect_mt<false>(sLeaves, num_leaves);
      } else {
        merkle_tree_utils::compute_blake_mt<false>(sLeaves, num_leaves);
      }
    }

    if (tid < blake3::CHAINING_VALUE_SIZE_U32) {
      mRoots(tid, blockIdx.x) = sLeaves(tid, 0);
    }
  }
};

}  // namespace pearl
