#!/usr/bin/env bash
# ARC-miner — HiveOS config generator.
# Translates the flight-sheet fields into arc-miner.conf (sourced by h-run.sh).
#
# Flight-sheet mapping:
#   Miner name .............. arc-miner (Setup Miner Config -> custom)
#   Hash algorithm .......... CUSTOM_ALGO   -> --algo   (prl|csd|rx|gr|nm, or dual e.g. prl+rx)
#   Wallet & worker template  CUSTOM_TEMPLATE -> --wallet [.--worker]
#   Pool URL ................ CUSTOM_URL    -> --pool   (scheme optional; defaults to stratum+tls://)
#   Pass ....................  (unused by arc-miner)
#   Extra config arguments .. CUSTOM_USER_CONFIG -> appended verbatim

[[ -t 1 ]] && . colors 2>/dev/null

cd "$(dirname "$BASH_SOURCE")" || exit 1
. h-manifest.conf

conf="$CUSTOM_CONFIG_FILENAME"

# --- algorithm -------------------------------------------------------------
ALGO="${CUSTOM_ALGO:-prl}"

# --- pool url (ensure a stratum scheme) ------------------------------------
POOL="$CUSTOM_URL"
case "$POOL" in
  *://*) : ;;                      # scheme already present, leave it
  "")    echo "h-config: CUSTOM_URL (Pool URL) is empty" >&2 ;;
  *)     POOL="stratum+tls://$POOL" ;;   # bare host:port -> assume TLS stratum
esac

# --- wallet + worker from the template -------------------------------------
# HiveOS has already expanded %WAL% / %WORKER_NAME% into CUSTOM_TEMPLATE.
# If the template carries an explicit ".worker" suffix, split it off; otherwise
# fall back to the rig's WORKER_NAME.
TEMPL="$CUSTOM_TEMPLATE"
if [[ "$TEMPL" == *.* ]]; then
  WALLET="${TEMPL%%.*}"
  WORKER="${TEMPL#*.}"
else
  WALLET="$TEMPL"
  WORKER="${WORKER_NAME:-arc}"
fi

# --- adapter (SYCL device selector) ----------------------------------------
# ONEAPI_DEVICE_SELECTOR is an ENV var, not a CLI flag, so it can't ride in the
# arc-miner args. Let the flight sheet pick it via an ADAPTER=<opencl|level_zero>
# token in "Extra config arguments"; we lift it out here into $ARC_SELECTOR, which
# h-run.sh exports as ONEAPI_DEVICE_SELECTOR.
#   ADAPTER=opencl      -> opencl:gpu      (DEFAULT; every box has an OpenCL ICD)
#   ADAPTER=level_zero  -> level_zero:gpu  (needs libze + render-group access)
# The default must match h-run.sh's own fallback — this file said level_zero
# while h-run.sh said opencl, and since nothing read $ARC_SELECTOR the mismatch
# was invisible.
SELECTOR="opencl:gpu"
EXTRA="$CUSTOM_USER_CONFIG"
if [[ "$EXTRA" =~ (^|[[:space:]])ADAPTER=([^[:space:]]+) ]]; then
  case "${BASH_REMATCH[2]}" in
    opencl|ocl)       SELECTOR="opencl:gpu" ;;
    level_zero|l0|ze) SELECTOR="level_zero:gpu" ;;
    *)                SELECTOR="${BASH_REMATCH[2]}" ;;   # raw pass-through (e.g. opencl:1)
  esac
  # Drop the ADAPTER=... token so it isn't handed to arc-miner as a bogus arg.
  EXTRA="$(sed -E 's/(^|[[:space:]])ADAPTER=[^[:space:]]+//g' <<<"$EXTRA")"
fi

# --- assemble args ---------------------------------------------------------
ARGS="--algo ${ALGO} --pool ${POOL} --wallet ${WALLET} --worker ${WORKER} --api-port ${CUSTOM_API_PORT}"
EXTRA="$(echo "$EXTRA" | xargs)"   # trim stray whitespace left by the token strip
[[ -n "$EXTRA" ]] && ARGS="$ARGS $EXTRA"

# Write the config that h-run.sh sources.
cat > "$conf" <<EOF
# Generated by h-config.sh $(date '+%F %T') — do not edit; edit the flight sheet.
ARC_ARGS="$ARGS"
ARC_SELECTOR="$SELECTOR"
EOF

echo "h-config: algo=$ALGO pool=$POOL wallet=${WALLET:0:10}… worker=$WORKER adapter=$SELECTOR api=$CUSTOM_API_PORT"

# --- arc-rx-shim slot injection (dual +rx) -----------------------------------
# Flight-sheet applies rewrite rig.conf and wipe MINER2. This script runs on
# every apply (and each agent stats cycle), so re-add the arc-rx-shim stats
# pseudo-miner whenever the algo has a CPU (+rx) leg. Idempotent no-op otherwise.
if [[ -d /hive/miners/arc-rx-shim && -w /hive-config/rig.conf ]]; then
  if [[ "$CUSTOM_ALGO $CUSTOM_USER_CONFIG" == *"+rx"* ]]; then
    if ! grep -q "^MINER2=arc-rx-shim" /hive-config/rig.conf; then
      if grep -q "^MINER2=" /hive-config/rig.conf; then
        sed -i "s/^MINER2=.*/MINER2=arc-rx-shim/" /hive-config/rig.conf
      else
        sed -i "/^MINER=/a MINER2=arc-rx-shim" /hive-config/rig.conf
      fi
      echo '{"status":"running"}' > /run/hive/miner_status.2 2>/dev/null
      echo "h-config: re-injected MINER2=arc-rx-shim (dual +rx)"
    fi
  fi
fi
