#!/usr/bin/env python3
"""Generate ignored static-switch headers for the torch-free C-ABI build.

Keep this script dependency-free. The C-ABI Makefile is used in slim build
containers and on profiling pods where the Python package build requirements
are not installed.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
GEMM_DIR = ROOT / "csrc" / "gemm"

MATMUL_CONFIGS = (
    (128, 256, 128, 64, 3, 1, 1),
    (128, 256, 128, 128, 3, 1, 1),
)

NOISING_A_CONFIGS = (
    (64, 64, 64, 2, "torch::kFloat16", "cutlass::half_t"),
    (64, 64, 64, 2, "torch::kInt32", "int"),
    (64, 64, 128, 2, "torch::kFloat16", "cutlass::half_t"),
    (64, 64, 128, 2, "torch::kInt32", "int"),
)

NOISING_B_CONFIGS = (
    (64, 64, 64, 2, "torch::kFloat16", "cutlass::half_t"),
    (64, 64, 64, 2, "torch::kInt32", "int"),
    (64, 64, 128, 2, "torch::kFloat16", "cutlass::half_t"),
    (64, 64, 128, 2, "torch::kInt32", "int"),
)


def write_lines(path: Path, lines: list[str]) -> None:
    # newline="\n" so the generated headers are LF on every platform — without
    # it, text-mode writes on Windows emit CRLF and churn the committed files.
    path.write_text("\n".join(lines) + "\n", newline="\n")


def write_matmul_switch(path: Path) -> None:
    lines = [
        "/* Do not edit -- generated by csrc/capi/generate_static_switches.py. */",
        "#define MATMUL_CONFIG_SWITCH(BM_VAR, BN_VAR, BK_VAR, R_VAR, "
        "STAGES_VAR, cM_VAR, cN_VAR, ...) \\",
        "\tdo { \\",
    ]
    for bm, bn, bk, r, stages, cm, cn in MATMUL_CONFIGS:
        lines.append(
            "\t\tMATMUL_CONFIG_OPTION(BM_VAR, BN_VAR, BK_VAR, R_VAR, "
            f"STAGES_VAR, cM_VAR, cN_VAR, {bm}, {bn}, {bk}, {r}, "
            f"{stages}, {cm}, {cn}, __VA_ARGS__); \\"
        )
    lines.append("\t} while(0)")
    write_lines(path, lines)


def write_noising_a_switch(path: Path) -> None:
    lines = [
        "/* Do not edit -- generated by csrc/capi/generate_static_switches.py. */",
        "#define NOISING_A_CONFIG_SWITCH(BM_VAR, BK_VAR, R_VAR, STAGES_VAR, "
        "AxEBL_TYPE_VAR, ...) \\",
        "\tdo { \\",
    ]
    for bm, bk, r, stages, torch_type, cutlass_type in NOISING_A_CONFIGS:
        lines.append(
            "\t\tNOISING_A_CONFIG_OPTION(BM_VAR, BK_VAR, R_VAR, STAGES_VAR, "
            f"AxEBL_TYPE_VAR, {bm}, {bk}, {r}, {stages}, "
            f"{torch_type}, {cutlass_type}, __VA_ARGS__); \\"
        )
    lines.append("\t} while(0)")
    write_lines(path, lines)


def write_noising_b_switch(path: Path) -> None:
    lines = [
        "/* Do not edit -- generated by csrc/capi/generate_static_switches.py. */",
        "#define NOISING_B_CONFIG_SWITCH(BN_VAR, BK_VAR, R_VAR, STAGES_VAR, "
        "EARxBpEB_TYPE_VAR, ...) \\",
        "\tdo { \\",
    ]
    for bn, bk, r, stages, torch_type, cutlass_type in NOISING_B_CONFIGS:
        lines.append(
            "\t\tNOISING_B_CONFIG_OPTION(BN_VAR, BK_VAR, R_VAR, STAGES_VAR, "
            f"EARxBpEB_TYPE_VAR, {bn}, {bk}, {r}, {stages}, "
            f"{torch_type}, {cutlass_type}, __VA_ARGS__); \\"
        )
    lines.append("\t} while(0)")
    write_lines(path, lines)


def main() -> None:
    GEMM_DIR.mkdir(parents=True, exist_ok=True)
    write_matmul_switch(GEMM_DIR / "static_switch_matmul.h")
    write_noising_a_switch(GEMM_DIR / "static_switch_noisingA.h")
    write_noising_b_switch(GEMM_DIR / "static_switch_noisingB.h")


if __name__ == "__main__":
    main()
